// import './functions/pipe';
// import './functions/compose';
// import './functions/all';
import './functions/prop';
// import './functions/props';
// import './functions/propEq';
// import './functions/pipeWith';
// import './functions/thunkify';
// import './functions/ap';
import './functions/sortBy';
